[package]
name = "web-core-wasm"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
bincode = { version = "2.0.1", features = ["std", "alloc", "serde"] }
js-sys = { workspace = true }
lazy_static = { workspace = true }
serde.workspace = true
serde-wasm-bindgen = "0.6.5"
serde_json.workspace = true
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = "0.4.55"
web-sys = { workspace = true, features = ["Element", "Document", "Window", "Event", "MessagePort", "MessageEvent", "EventListener", "AddEventListenerOptions", "HtmlCollection"] }
